---
stages:
  - publish

include:
  - remote: "https://gitlab.com/dudefellah/ci-templates/-/raw/master/ansible/Galaxy.gitlab-ci.yml"

galaxy_publish:
  stage: publish
  extends: .ansible_galaxy_publish
  tags:
    - docker-socket-runner
