---
stages:
  - publish

include:
  - project: "gitlab.com/dudefellah/ci-templates"
    ref: "master"
    file: "ansible/Galaxy.gitlab-ci.yml"

galaxy_publish:
  image: ansible/ansible-runner
  extends: .ansible_galaxy_publish
